version: '3'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn main:app --host=0.0.0.0 --port=3000
    volumes:
      - ./app:/app
    ports:
      - '3000:3000'
    networks:
      - fastapi-network
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3.8.14-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    hostname: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - fastapi-network

networks:
  fastapi-network:
    driver: bridge
